
name: test, build and push

on:
  push:
   branches: [main]
  pull_request:
   branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: npm install
        run: npm i
        working-directory: ./frontend

      - name: run tests
        run: npm run test
        working-directory: ./frontend

  build:
    needs: test
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
          
      - name: docker build frontend
        run: docker build ./frontend -t frontend

      - name: docker build backend
        run: docker build ./backend -t backend

      - name: docker push
        run: |
          docker push frontend ${{ secrets.DOCKER_USERNAME }}/uptime-monitor
          docker push backend ${{ secrets.DOCKER_USERNAME }}/uptime-monitor
          

