
name: test, build and push

on:
  push:
   branches: [main]
  pull_request:
   branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: action/checkout@v3

      - name: use Node.js ${{matrix.node-version}}
        uses: action/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm i
        working-directory: ./frontend

      - name: run tests
        run: npm run test
        working-directory: ./frontend
